---
Gemfile:
  optional:
    ':test':
      - gem: 'compare-xml'
.rubocop.yml:
  inherit_from: .rubocop_todo.yml
.travis.yml:
  secure: "HNUiBJlE/HoxJnuCK08ZZB0bJGtVB0VygZJ6L1HTBj5FkZFylaj4iVn4/HeaEf9OOUgupXsraZ56Ai3D+XO60GM7gbSe7rYJfRu1ZtXE5BjBOzvEinsObqW/MQU/j+WphwKpvskmLaxKExhMgbno+lhM3CwWUoiFzZxfg9byxfzG6B2lt0xkuy3JInjUlkeWrYYZ4HDCo5P58rDCCCxclWeM0cjRF+P6/g3z06pueknOQ7lALMKAhcTHDwQKjNQn3iYr9c9ro+xwTBpkn6sruNP4r85xWHjPKFCNg4Kv82eRyAZqTzL/UnqmgwcLTNAN20CRI7PTrgiu0fENROeNA/cbPt4J7FDFFlDyNPDlYO6y9sOpKvjnEmO9bakIoClm4OhLh4sLoLV7IfdkllW2eWjnI7FntKUyW3ok8W8KUbxIkGHA4joLB2CYauu2xhaitTNx32gm8LExU5WD9Mf49uA6jfnxBr+IDiDNX7wWgcnCAOufpTwIGVxlhiWLsPeG2mM1TQccAXK1ySc1MpAvZ/XWnRyt8E3ntaXBo/ewlnX0Ep0gm+xStfGiVKkBEgqDUpKj9KWZgGb/+Ku/H9obeX05XNnmpJy2fIj5xV5pMinvsdtqnV3U6q3TMl1ar+T0Sftb6lkFifGcVvv6L5sDe5RWOHd57MAjFbxy4h2X5dk="
