---
os: linux
dist: bionic
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
jobs:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  username: puppet
  password:
    secure: "HNUiBJlE/HoxJnuCK08ZZB0bJGtVB0VygZJ6L1HTBj5FkZFylaj4iVn4/HeaEf9OOUgupXsraZ56Ai3D+XO60GM7gbSe7rYJfRu1ZtXE5BjBOzvEinsObqW/MQU/j+WphwKpvskmLaxKExhMgbno+lhM3CwWUoiFzZxfg9byxfzG6B2lt0xkuy3JInjUlkeWrYYZ4HDCo5P58rDCCCxclWeM0cjRF+P6/g3z06pueknOQ7lALMKAhcTHDwQKjNQn3iYr9c9ro+xwTBpkn6sruNP4r85xWHjPKFCNg4Kv82eRyAZqTzL/UnqmgwcLTNAN20CRI7PTrgiu0fENROeNA/cbPt4J7FDFFlDyNPDlYO6y9sOpKvjnEmO9bakIoClm4OhLh4sLoLV7IfdkllW2eWjnI7FntKUyW3ok8W8KUbxIkGHA4joLB2CYauu2xhaitTNx32gm8LExU5WD9Mf49uA6jfnxBr+IDiDNX7wWgcnCAOufpTwIGVxlhiWLsPeG2mM1TQccAXK1ySc1MpAvZ/XWnRyt8E3ntaXBo/ewlnX0Ep0gm+xStfGiVKkBEgqDUpKj9KWZgGb/+Ku/H9obeX05XNnmpJy2fIj5xV5pMinvsdtqnV3U6q3TMl1ar+T0Sftb6lkFifGcVvv6L5sDe5RWOHd57MAjFbxy4h2X5dk="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
